config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :diarys do
    resources :notes
  end
  root 'diarys#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
# frozen_string_literal: true

# Diary model
class Diary < ApplicationRecord
  # scope for worker to delete old diarys
  scope :old, -> { where('expiration < ?', Time.now) }
  has_many :notes
  enum kind: %i[pub priv]

  validates :kind, presence: true
  validates :title, presence: true
  validates :expiration, absence: true, if: :public?

  def public?
    kind == 'pub'
  end
end

app/models/note.rb
# frozen_string_literal: true

# Note model. nothing special, just belongs to.
class Note < ApplicationRecord
  belongs_to :diary
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/diarys_controller.rb
# frozen_string_literal: true

# Main diarys controller. CRUD here.
class DiarysController < ApplicationController
  def index
    diarys = Diary.all.order('created_at DESC')
    render json: { status: 'SUCCESS', message: 'Loaded diarys', data: diarys }, status: :ok
  end

  def show
    diary = Diary.find(params[:id])
    render json: { status: 'SUCCESS', message: 'Loaded diary', data: diary }, status: :ok
  end

  def create
    diary = Diary.new(diary_params)
    if diary.save
      render json: { status: 'SUCCESS', message: 'Saved diary', data: diary }, status: :ok
    else
      render json: { status: 'ERROR', message: 'Diary not saved', data: diary }, status: :unprocessable_entity
    end
  end

  def destroy
    diary = Diary.find(params[:id])
    diary.destroy
    render json: { status: 'SUCCESS', message: 'Deleted diary', data: diary }, status: :ok
  end

  def update
    diary = Diary.find(params[:id])
    if diary.update(diary_params)
      render json: { status: 'SUCCESS', message: 'Updated diary', data: diary }, status: :ok
    else
      render json: { status: 'ERROR', message: 'Diary not updated', data: diary }, status: :unprocessable_entity
    end
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :expiration, :kind)
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

# Main notes controller. CRUD here.
class NotesController < ApplicationController
  def create
    diary = Diary.find(params[:diary_id])
    note = diary.notes.create(params[:note].permit(:text))
    render json: { status: 'SUCCESS', message: 'Note added', data: note }, status: :ok
  end

  def destroy
    diary = Diary.find(params[:diary_id])
    note = diary.notes.find(params[:id])
    note.destroy
    render json: { status: 'SUCCESS', message: 'Note deleted', data: note }, status: :ok
  end

  def update
    diary = Diary.find(params[:diary_id])
    note = diary.notes.find(params[:id])
    if diary.notes.update(params[:note].permit(:text))
      render json: { status: 'SUCCESS', message: 'Updated note', data: note }, status: :ok
    else
      render json: { status: 'ERROR', message: 'Note not updated', data: note }, status: :unprocessable_entity
    end
  end

  def show
    diary = Diary.find(params[:diary_id])
    note = diary.notes.find(params[:id])
    render json: { status: 'SUCCESS', message: 'Loaded note', data: note }, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diarys_helper.rb
module DiarysHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/diarys/_form_edit.html.erb
<div class="section">
<%= simple_form_for @diary do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :expiration, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  
  <div class="asd">
    <%= f.input :kind, input_html: { class: 'select' }, wrapper: false, :collection => %w[pub priv] %>
  </div>
  <%= f.button :submit, class: "button is-primary" %>
<% end %>
</div>

app/views/diarys/_form_new.html.erb
<div class="section">
<%= simple_form_for @diary, url: diarys_path(@diary) do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :expiration, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  
  <div class="asd">
    <%= f.input :kind, input_html: { class: 'select' }, wrapper: false, :collection => %w[pub priv] %>
  </div>
  <%= f.button :submit, class: "button is-primary" %>
<% end %>
</div>

app/views/diarys/edit.html.erb
<% content_for :page_title, "Edit Diary" %>
<%= render 'form_edit' %>

app/views/diarys/index.html.erb
<% content_for :page_title, "Index"%>

<h1 class="title"> Diary index<h1>
<section class="section">
    <div class="container">.
        <% @diarys.each do |diary| %>
        <div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to diary.title, diary  %></p>
		      </div>
		    </div>
		    <div class="content">
		     	<%= diary.expiration %>
                <%= diary.kind %>
		    </div>
		  </div>
		</div>
            
        <% end %>
    </div>
</section>

app/views/diarys/new.html.erb
<% content_for :page_title, "Create a new diary" %>
<%= render 'form_new' %>

app/views/diarys/show.html.erb
<% content_for :page_title, @diary.title %>

<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong>Actions</strong>
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">
		  	<p class="level-item">
		    	<%= link_to "Edit", edit_diary_path(@diary), class:"button" %>
		  	</p>
		  	<p class="level-item">
				<%= link_to "Delete", diary_path(@diary), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
				</p>
		  </div>
		</nav>
		<hr/>

		<div class="content">
			<%= @diary.expiration %>
            <%= @diary.kind %>
		</div>
	</div>
</section>

<section class="section notes">
	
	<div class="container">
		<h2 class="subtitle is-5"><strong><%= @diary.notes.count %></strong> Notes</h2>
		<%= render @diary.notes %>
		<div class="note-form">
			<hr />
			<h3 class="subtitle is-3">Post your note</h3>
	 		<%= render 'notes/form' %>
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoDiarys</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<section class="hero is-primary is-medium">
	  <!-- Hero head: will stick at the top -->
	  <div class="hero-head">
	    <nav class="navbar">
	      <div class="container">
	        <div class="navbar-brand">
	          <%= link_to 'Demo Diarys', root_path, class: "navbar-item" %>
	          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
	            <span></span>
	            <span></span>
	            <span></span>
	          </span>
	        </div>
	        <div id="navbarMenuHeroA" class="navbar-menu">
	          <div class="navbar-end">
	            <%= link_to "Create New Diary", new_diary_path, class:"navbar-item" %>
	          </div>
	        </div>
	      </div>
	    </nav>
	  </div>

	  <!-- Hero content: will be in the middle -->
	  <div class="hero-body">
	    <div class="container has-text-centered">
	      <h1 class="title">
	        <%= yield :page_title %>
	      </h1>
	    </div>
	  </div>
	</section>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for([@diary, @diary.notes.build]) do |f| %>
<!--
collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
-->

<div class="field">
  <div class="control">
    <%= f.input :text, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
  </div>
</div>
<%= f.button :submit, 'Post note', class: "button is-primary" %>
<% end %>

app/views/notes/_note.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <%= note.text %>
        </p>
      </div>
    </div>
     <!--> TODO: notes edit buttons <-->
      <%= link_to 'Delete', [note.diary, note], method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>

</div>

app/views/notes/edit.html.erb
<% content_for :page_title, "Edit Note" %>
<%= render 'form' %>